### ISSUE TITLE
Rendering is not working properly

### ISSUE THREAD

**Issue by Julie-Fabre** [Tomaubier/CoperniFUS#2]
Hi, 

Rendering is not working properly for me in CoperniFUS (see attached screenshot). Could you suggest some ways to debug?
I have blender installed (and rendering inside blender is working).
I am running Ubuntu 24.04 on a Framework Laptop 13 with an Intel® Core™ Ultra 7 165H × 22 processor, Intel® Arc™ Graphics (MTL) and 64GiB of RAM.
I also get the same error on a Windows 11 desktop with 128GB RAM, 13th Gen Intel(R) Core(TM)i7-13700K processor and 12GB NVIDIA GeForce RTX 4070 Graphics card. 

![Image](https://github.com/user-attachments/assets/10e09a40-a60b-4c10-87ae-c3b9b8388543)

**Comment by Tomaubier** [comment]
Hi,
Thanks for the feedback! Unfortunately I haven’t encountered this issue yet. Blender is only required in this project to perform boolean operations (Blender is one of `trimesh`’s boolean engine). The rendering engine is using `opengl` via `pyqtgraph`.

From your screenshot it seems that the abnormal behavior is only impacting volumetric data rendering. This is handled by `pyqtgraph`’s [GLVolumeItem](https://pyqtgraph.readthedocs.io/en/latest/api_reference/3dgraphics/glvolumeitem.html) method. A quick way to test if `GLVolumeItem` behaves correctly is to run `pyqtgraph`’s Volumetric example.
1. Within the python environnement in which CoperniFUS is installed you can run
   `python -m pyqtgraph.examples`
2. A GUI should pop up, in the `3D graphics` section in the left panel, double click on `Volumetric`
For reference this is the expected output:
<img width="1171" alt="Image" src="https://github.com/user-attachments/assets/d4847b18-7929-4ee0-a191-657fb16ba5d7" />

If the example runs as expected, the issue has to lie in my code! A `pyqtgraph` or `OpenGL` should be returned in the console.. Just to make sure that `CoperniFUS`’s internal console does not hide any error message from us the latter can be disabled entirely by setting `disable_internal_console` to `True`. When using `CopeniFUS` in standalone mode (launched from a terminal) this option can be set as follows:
`CoperniFUS --disable_internal_console True`
> I’ve just made this argument available from the console, make sure to update CoperniFUS before trying by running
> 1. `pip uninstall CoperniFUS`
> 2. `pip install git+https://github.com/Tomaubier/CoperniFUS.git`

Let me know how this goes.

Best,

Tom

**Comment by Tomaubier** [comment]
Looking back at `pyqtgraph`’s `GLVolumeItem` documentation, it appears that the function is expecting arrays in the `ubytes` type. In my implementation of the BrainAtlas module, I’m providing `GLVolumeItem` with integers ranging from 0 to 255 but still in the `float64` type. For some reason this didn’t cause any issues on my side but some GPUs might not handle this.

I have just pushed an update with this fix, please try it out me let me know how it goes.

Best,

Tom

**Comment by Julie-Fabre** [comment]
Hi Tom,

Thanks a lot for the detailed explanations!
To answer your points:
- Testing GLVolumeItem everything looks fine (see below)

![Image](https://github.com/user-attachments/assets/7babb227-4cc2-4f39-9168-7d647d66a661)
- Thanks for the code updates! I still get this error with your most recent push and I don't see any error messages printed in the shell
This is irrespective of OS - I still get errors on both Linux and Windows. 

Let me know if you have any more ideas to debug! :)

**Comment by Tomaubier** [comment]
Ok that's good, however things are getting a bit more confusing to me! ^^
As mentioned in [issue#3](https://github.com/Tomaubier/CoperniFUS/issues/3#issuecomment-2877471463) I managed to get everything to run on Ubuntu 24.04. Given the validation I did on windows 11 it doesn't look like it is an OS-related problem..

I'm still trying to think of an intermediate test that could reveal the bug. Out of curiosity, what is happening when you try to pan or rotate the view? Is the viewer responsive? Have you tried changing the resolution of the atlas or the altas type?

> By the way I realize writing this that the resolution selector is not very obvious when getting started with CoperniFUS. I will update the UI to make the existence of this option more obvious because this parameter can drastically change the atlas appearance.

### Atlas rendering stride of 10
<img width="1574" alt="Image" src="https://github.com/user-attachments/assets/ff05e91e-b678-4b02-9d93-4f09d149b680" />

### Atlas rendering stride of 1
<img width="1574" alt="Image" src="https://github.com/user-attachments/assets/5c3c1cd1-d215-4acd-902d-6854066c6e37" />

**Comment by Julie-Fabre** [comment]
Hi Tom, 
Frustratingly, I am not sure what combination of re-installing etc did it, but everything seems to be working fine now :) 

![Image](https://github.com/user-attachments/assets/d1efc57d-e14b-4096-ab6d-1f0c2eb36dc2)

**Comment by Tomaubier** [comment]
Ok thanks for the update, I will keep an eye on this problem going forward.
